# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kA3axjXilf8NBi0szlj1GhVWQUPtR488
"""

def kasallik_tashxisi(belgi):
  if  belgi == "Istima":
    return  "Paratsetamol iching"
  elif belgi == "Bosh og'rig'i":
    return  "Bolnol"
  elif belgi == "Tish og'rig'i":
   return  "Senepar"
  elif belgi == "Quloq og'rig'i":
    return "Ibuprofen iching"
  elif belgi == "Tomoq og'rig'i":
    return " Anzibel iching"
  elif belgi == "Qorin og'rig'i":
    return "Lineks iching"
  elif belgi == " Bo'g'im og'rig'i":
    return "Artoksan iching "
  elif belgi == "Oshqozon og'rishi":
    return "Ibuklin iching "
  elif belgi == "Shamollash":
    return "Tylol hot iching"
  else:
    return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting"  )
natija=kasallik_tashxisi(belgi)
print(natija)

def  mashina_nomerlari(raqam):
  if raqam == "60":
   return "Andijon"
  elif raqam == "50":
   return "Namangan"
  elif raqam == "40":
   return "Farg'ona"
  elif raqam == "01":
   return "Toshkent shahri"
  elif raqam == "10":
   return "Toshkent "
  elif raqam == "20":
   return "Sirdaryo"
  elif raqam == "30":
   return "Samarqand"
  elif raqam == "70":
   return "Qashqadaryo"
  elif raqam == "75":
   return "Surxondaryo"
  elif raqam == "80":
   return "Buxoro"
  elif raqam == "85":
   return "Navoiy"
  elif raqam == "90":
   return "Xorazm"
  elif raqam == "50":
   return "Qoraqalpog'iston Respublikasi"
  else:
    return "Bunday hudud yo'q "
raqam=input("Mashinaning hudud raqamini kiriting: "  )
natija=mashina_nomerlari(raqam)
print(natija)